version: 0.0
os: linux
files:
  - source: /
    destination: /myCodeDeployDemo
permissions:
  - object: /myCodeDeployDemo
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: Scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/start.sh
      runas: ec2-user
